monitor=DP-1,1920x1080@180,auto,1
input {
    kb_layout = es
}
general {
    gaps_in = 5
    gaps_out = 10
    border_size = 2
}
decoration {
    rounding = 5
}
animations {
    enabled = false
}
misc {
    on_focus_under_fullscreen = 2
}
binds {
    movefocus_cycles_fullscreen = true
}
$terminal = kitty
bind = SUPER, RETURN, exec, $terminal
bind = SUPER, X, killactive
bind = SUPER, T, exec, kitty
bind = SUPER, 1, workspace, 1
bind = SUPER, 2, workspace, 2
bind = SUPER, 3, workspace, 3
bind = ALT, Tab, exec, ~/.config/hypr/scripts/toggle-minimize.sh
bind = , Print, exec, hyprshot -m region

bindm = SUPER, mouse:273, resizewindow

bind = SUPER, mouse:275, togglefloating
bindm = SUPER, mouse:272, movewindow


exec-once = snixembed --fork
# exec-once = python3 $HOME/.config/hypr/minimize-rescue.py
env = DISPLAY, :1
env = XDG_SESSION_TYPE, wayland
env = WAYLAND_DISPLAY, wayland-1
exec-once = quickshell --no-detailed-logs
exec-once = hyprpaper
exec-once = $HOME/.config/quickshell/scripts/clipboard-persist.sh
exec-once = $HOME/.config/quickshell/scripts/restore-session.sh



