# Kitty minimal config para Hyprland + Starship
# font_family JetBrainsMono Nerd Font
font_size 11

cursor_shape block
scrollback_lines 2000

enable_audio_bell no

# buen comportamiento general
confirm_os_window_close 0

shell bash --login --norc

include gruvbox-dark.conf

# BEGIN_KITTY_FONTS
font_family      family='JetBrainsMono Nerd Font' postscript_name=JetBrainsMonoNF-Regular
bold_font        auto
italic_font      auto
bold_italic_font auto
# END_KITTY_FONTS